### ISSUE TITLE
Add Ant build file

### ISSUE THREAD

**Issue by takeshixx** [f-block/gunziper#5]
In order to improve the process of building the extension JAR, Ant could help to automate this step.

Additionally, basic documentation for creating the extension JAR manually should be added to either the README.md or a repository wiki.

**Comment by bluec0re** [comment]
Gradle could also be an option

**Comment by takeshixx** [comment]
Gradle support has been introduced in 745328cf24deb82ecb362cd5b218a33b90f39131.
